// <auto-generated />
using System;
using BigMission.Database.V2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigMission.Database.V2.Migrations
{
    [DbContext(typeof(ContextV2))]
    [Migration("20241129191142_CarTableConfig")]
    partial class CarTableConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo2")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.ColumnDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("CarStatusTableColumnDefinitions", "dbo2");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarStatusTableConfiguration", "dbo2");
                });

            modelBuilder.Entity("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.ColumnDefinitionOverride", b =>
                {
                    b.HasBaseType("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.ColumnDefinition");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("ConfigurationId1")
                        .HasColumnType("int");

                    b.HasIndex("ConfigurationId1");

                    b.ToTable("CarStatusTableColumnOverrides", "dbo2");
                });

            modelBuilder.Entity("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.ColumnDefinition", b =>
                {
                    b.HasOne("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.Configuration", null)
                        .WithMany("Columns")
                        .HasForeignKey("ConfigurationId");
                });

            modelBuilder.Entity("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.ColumnDefinitionOverride", b =>
                {
                    b.HasOne("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.Configuration", null)
                        .WithMany("ColumnOverrides")
                        .HasForeignKey("ConfigurationId1");

                    b.HasOne("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.ColumnDefinition", null)
                        .WithOne()
                        .HasForeignKey("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.ColumnDefinitionOverride", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BigMission.Database.V2.Models.UI.Channels.CarStatusTable.Configuration", b =>
                {
                    b.Navigation("ColumnOverrides");

                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
